[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "enigma2"
version = "2.4.2"
description = "Enigma2 encryption and decryption module"
authors = [
    { name="r00st3r", email="s1llyr00st3r@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "chardet",
    "pydantic"
]

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["enigma2"]

[project.scripts]
enigma2-cipher = "enigma2.core.enigma2_cipher:main"

[tool.setuptools.package-data]
"*" = ["LICENSE.txt"]

[tool.pytest.ini_options]
testpaths = ["tests"]
