import unittest
import numpy as np
import os
from pathlib import Path
import sys

from enigma2.enigma2 import E2
from enigma2.enigma2_config import E2Config
import random

class TestE2(unittest.TestCase):
    def setUp(self):
        self.pwd = b"testpassword"
        # It is always recommended to use a dict to initialize E2Config instead of using pwd for testing purposes
        config_data = {
            "btype": 256,
            "dtype": np.uint8,
            "rotations_seed": 1700,
            "number_rotors": 1,
            "rotors_seed": 1701,
            "noise_size": 10000,
            "noise_seed": 1702,
            "plugboard_size": 2,
            "plugboard_seed": 1703
        }
        self.config = E2Config(self.pwd, **config_data)
        # print(self.config.plugboard_size)
        self.e2 = E2(config=self.config)
        self.testing_files_path = Path(os.path.dirname(__file__)).parent.joinpath("tests/testing_files")

    def test_random_key_generation(self):
        """
        Verifies that the random key generated by the E2 object is consistent with the provided password.
        """
        random_key = E2.gen_key(32)
        self.assertEqual(len(random_key), 32)
        self.assertIsInstance(random_key, bytes)

    # for Generator?
    def test_rotor_shapes(self):
        """
        Verifies that the shapes of the encryption and decryption rotors are consistent with
        the parameters provided during initialization.
        """
        self.assertEqual(self.e2.encryption_rotors.shape, (self.e2.config.number_rotors, self.config.btype))
        self.assertEqual(self.e2.decryption_rotors.shape, (self.e2.config.number_rotors, self.config.btype))

    def test_encrypt_decrypt_identity_easy(self):
        """
        Verifies that encryption followed by decryption results in the original data.
        This test also verifies that the state of the E2 object is properly reset after
        encryption and decryption operations.
        """
        data = np.arange(20, dtype=self.config.dtype)
        encrypted = self.e2.encrypt(data.copy())
        # Now it is optional to reset the rng, but it is sometimes useful
        # self.e2.reset_rng()
        decrypted = self.e2.decrypt(encrypted.copy())
        np.testing.assert_array_equal(decrypted, data)

    def test_encrypt_decrypt_identity_hard(self):
        """
        The same as test_encrypt_decrypt_identity_easy but with random data multiple times    
        """
        for i in range(10):
            random_rng = np.random.default_rng(i)
            data = random_rng.integers(0, self.config.btype, size=20, dtype=self.config.dtype)
            encrypted = self.e2.encrypt(data)
            decrypted = self.e2.decrypt(encrypted)
            np.testing.assert_array_equal(decrypted, data)

    def test_rotor_permutation(self):
        """
        Verifies that all rotors are permutations of [0, 1, ..., btype-1].
        It is unnessary to check it because it does not affect the encryption process
        Though if it fails, it could be your lucky day...
        """
        for i in range(self.e2.config.number_rotors):
            rotor = self.e2.encryption_rotors[i]
            rotor_unique_elements = np.unique(rotor)
            self.assertEqual(len(rotor_unique_elements), self.config.btype)
            self.assertTrue(np.all(rotor_unique_elements==np.arange(self.config.btype, dtype=self.config.dtype)))

    def test_encryption_changes_data_easy(self):
        """
        Verifies that the encryption operation actually changes the input data.

        Collisions are more likely to happen with small amounts of data
        """
        data = np.arange(20, dtype=self.config.dtype)
        encrypted = self.e2.encrypt(data.copy())
        self.assertFalse(np.array_equal(encrypted, data))

    def test_encryption_changes_data_hard(self):
        """
        The same as test_encryption_changes_data_easy but with random data multiple times    
        """
        for i in range(1000):
            random_rng = np.random.default_rng(random.randint(0, 1000000))
            data = random_rng.integers(0, self.config.btype, size=20, dtype=self.config.dtype)
            encrypted = self.e2.encrypt(data.copy())
            self.assertFalse(np.array_equal(encrypted, data))

    def test_cipher_with_original_rotations(self):
        """
        Verifies that the original rotations of enigma can be used successfully with e2 
        """
        # set original rotations to True
        self.config.original_rotations = True
        e2_original = E2(config=self.config)
        data = np.arange(20, dtype=e2_original.config.dtype)
        encrypted_original = e2_original.encrypt(data.copy())
        decrypted_original = e2_original.decrypt(encrypted_original.copy())
        self.assertEqual(np.array_equal(decrypted_original, data), True)
    
    def test_encrypt_decrypt_identity_for_files(self):
        e2 = E2(config=self.config)
        # self.config.verbose = True
        # e2.reset_rng()
        pdf_path = self.testing_files_path.joinpath("testing_doc.pdf")
        # print(pdf_path)
        pdf_encrypted_path = e2.encrypt_file(pdf_path)
        # print(pdf_encrypted_path)
        # e2.reset_rng()
        pdf_decrypted_path = self.e2.decrypt_file(pdf_encrypted_path, self.testing_files_path.joinpath("decrypted"))
        # print(pdf_decrypted_path)
        self.assertEqual(pdf_path.read_bytes(), pdf_decrypted_path.read_bytes())
    
    def test_encrypt_decrypt_identity_for_different_dtypes(self):
        # there is no encoding that supports np.uint64
        all_valid_dtypes = [np.uint8, np.uint16]#, np.uint32]
        dtypes_valid_encodings = ["utf-8", "utf-16"]#, "utf-32"]
        for uint_dtype, encoding in zip(all_valid_dtypes, dtypes_valid_encodings):
            config_data = {
                "dtype": uint_dtype,
                "rotations_seed": 1700,
                "number_rotors": 1, # if too much rotors are generated with high dtype (uint32) it will overcome ram capacity
                # so it is better to use uint8 or uint16 for the best time-resources performance 
                "rotors_seed": 1701,
                "noise_size": 10,
                "noise_seed": 1702,
                "plugboard_size": 2,
                "plugboard_seed": 1703,
                "encoding": encoding
            }
            config = E2Config(self.pwd, **config_data)    
            e2 = E2(config=config)
            for i in range(10):
                random_rng = np.random.default_rng(i)
                data = random_rng.integers(0, self.config.btype, size=20, dtype=self.config.dtype)
                encrypted = e2.encrypt(data)
                decrypted = e2.decrypt(encrypted)
                np.testing.assert_array_equal(decrypted, data)

    def test_encrypt_decrypt_identity_for_files_with_different_dtypes(self):
        """
        Test the encryption and decryption of files with different dtypes and their corresponding encodings.

        It uses the same logic as test_encrypt_decrypt_identity_for_files but with different dtypes and their corresponding encodings.

        This test is useful to check if the encryption and decryption process works correctly for different dtypes and their corresponding encodings.
        
        It is commented beacuse i need to apply the multithreading to the encryption and decryption process to make it faster and lighter.
        In current version we create objects that consume a lot of memory
        """        

        # all_valid_dtypes = [np.uint8, np.uint16, np.uint32]
        # dtypes_valid_encodings = ["utf-8", "utf-16", "utf-32"]
        # for uint_dtype, encoding in zip(all_valid_dtypes, dtypes_valid_encodings):
        #     config_data = {
        #         "dtype": uint_dtype,
        #         "rotations_seed": 1700,
        #         "number_rotors": 1, # if too much rotors are generated with high dtype (uint32) it will overcome ram capacity
        #         "rotors_seed": 1701,
        #         "noise_size": 10000,
        #         "noise_seed": 1702,
        #         "plugboard_size": 2,
        #         "plugboard_seed": 1703,
        #         "encoding": encoding
        #     }
        #     config = E2Config(self.pwd, **config_data)    
        #     e2 = E2(config=config)
        #     for i in range(10):
        #         random_rng = np.random.default_rng(i)
        #         data = random_rng.integers(0, self.config.btype, size=20, dtype=self.config.dtype)
        #         encrypted = e2.encrypt(data)
        #         decrypted = e2.decrypt(encrypted)
        #         np.testing.assert_array_equal(decrypted, data)
        pass

if __name__ == "__main__":
    unittest.main()